---

name: deploy demo
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/aereal/enjoy-github-custom-deployment-protection-rules
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
      - run: echo 'Deployed'
