---

name: deploy
on:
  workflow_call:
    inputs:
      group:
        type: string
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/aereal/enjoy-github-custom-deployment-protection-rules
    concurrency:
      group: ${{ inputs.group }}
      cancel-in-progress: true
    steps:
      - run: echo 'Deployed'
