---

name: manually deploy
on:
  workflow_dispatch:
    inputs:
      group:
        required: true
        description: deployment target environment
        type: environment
jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yml
    with:
      group: ${{ inputs.group }}
